version: '3.3'

services:
  postgres:
    image: postgres:15
    container_name: mcp-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mcp
    ports:
      - "5432:5432"
    volumes:
      - ./network/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

  nextjs:
    build:
      context: .
    container_name: mcp-nextjs
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/mcp
    depends_on:
      - postgres

volumes:
  db_data: {} 
